name: DEV/UAT ADF Deployment

on:
  workflow_dispatch:
  # push:
  #   branches: develop
  

    inputs:
      branch:
        description: 'Specify the branch to deploy code from'
        required: true
        default: 'develop'

      environment:
        description: 'Choose the environment'
        required: true
        default: 'dev'  
        type: choice
        options:
          - dev
          - uat

env:
  branch: ${{github.event.inputs.branch || 'develop'}}
  environment: ${{github.event.inputs.environment || 'dev'}}     
  PYTHON_VERSION: 3.8
  NODE_VERSION: 20

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  Validate-ARM:
    name: Validate ARM Template
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: CheckOut Repository
        uses: actions/checkout@v4

# Installs Node and the npm packages saved in your package.json file in the build
      - name: Install Node.JS ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
         node-version: ${{env.NODE_VERSION}}
      
      - name: Install npm packages
        run: npm install
        working-directory: '${{github.workspace}}/'

      - name: Validate ARM Template
        run: |
         npm run build validate ${{github.workspace}}/ /subscriptions/6b972f7e-adb4-42c8-aa18-4bfcd1aec15f/resourceGroups/RAHUL-ADF-DEV/providers/Microsoft.DataFactory/factories/rahuladfdevadf

  Build-ARM:
    name: Build ARM Teamplate
    runs-on: ubuntu-latest
    needs: Validate-ARM
    environment: dev

    steps:
      - name: CheckOut Repository
        uses: actions/checkout@v4

# Installs Node and the npm packages saved in your package.json file in the build
      - name: Install Node.JS ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
         node-version: ${{env.NODE_VERSION}}
      
      - name: Install npm packages
        run: npm install
        working-directory: '${{github.workspace}}/'
        
      - name: Export ARM Templates
        working-directory: '${{github.workspace}}/'
        run: | 
         npm run build export ${{github.workspace}}/ /subscriptions/6b972f7e-adb4-42c8-aa18-4bfcd1aec15f/resourceGroups/RAHUL-ADF-DEV/providers/Microsoft.DataFactory/factories/rahuladfdevadf "ExportedArmTemplate"
      
      - name: Publish ARM Template Artifact
        uses: actions/upload-artifact@v3
        with:
         name: ExportedArmTemplate # (4) use the same artifact name you used in the previous export step
         path: ${{github.workspace}}/ExportedArmTemplate

  Deploy-ADF-DEV:
    name: Deploy ADF to DEV
    runs-on: ubuntu-latest
    needs: Build-ARM
    if: ${{ github.event.inputs.environment == 'dev' }}
    environment: dev
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3


      - name : List ARM Template
        run: |
         ls -R
      
      - name: Az CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy ADF Resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{vars.RESOURCE_GROUP}}
          dataFactoryName: ${{vars.DATA_FACTORY}}
          armTemplateFile: ExportedArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: ExportedArmTemplate/ARMTemplateParametersForFactory.json

