
name: First Workflow

on:
  push:
    branches: ["main"]

jobs:
  read-README:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Read-README
      run : cat README.md

    - name: Echo-to-file
      run: echo "My name is Rahul" > Rahul.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
         name: my-artifact
         path: Rahul.txt # or path/to/artifact
