
name: First Workflow

on:
  push:
    branches: ["main"]

jobs:
  Upload-Artifact:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Read-README
      run : cat README.md

    - name: Echo-to-file
      run: echo "My name is Rahul" > Rahul.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
         name: my-artifact
         path: Rahul.txt # or path/to/artifact
  Cat-File:
    needs: Upload-Artifact
    runs-on: ubuntu-latest
    steps: 
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
         name: my-artifact

    - name: Read File
      run: cat Rahul.txt
       
    
