
name: First Workflow

on:
  push:
    branches: ["main"]

jobs:
  read README:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Read README
      run : cat README.md
